# Generated by Django 2.2 on 2019-04-20 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('github_account_link', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('website', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stemmer',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('license', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('documentation_link', models.CharField(max_length=255, null=True)),
                ('download_link', models.CharField(max_length=255, null=True)),
                ('how_to_use', models.TextField(null=True)),
                ('authors', models.ManyToManyField(to='stemmers_comparer.Author')),
                ('features', models.ManyToManyField(to='stemmers_comparer.Feature')),
                ('programming_languages', models.ManyToManyField(to='stemmers_comparer.ProgrammingLanguage')),
                ('requirements', models.ManyToManyField(to='stemmers_comparer.Requirement')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email_address', models.EmailField(max_length=254)),
                ('user_github_account_link', models.CharField(max_length=255, null=True)),
                ('comment', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now=True)),
                ('stemmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stemmers_comparer.Stemmer')),
            ],
        ),
    ]
