# Generated by Django 2.2 on 2019-04-23 21:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('github_account_link', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stemmer',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=80)),
                ('is_enabled', models.BooleanField(default=True)),
                ('license', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('documentation_link', models.URLField(blank=True, null=True)),
                ('download_link', models.URLField(blank=True, null=True)),
                ('how_to_use', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('average', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('authors', models.ManyToManyField(blank=True, to='stemmers_comparer.Author')),
                ('features', models.ManyToManyField(blank=True, to='stemmers_comparer.Feature')),
                ('programming_languages', models.ManyToManyField(blank=True, to='stemmers_comparer.ProgrammingLanguage')),
                ('requirements', models.ManyToManyField(blank=True, to='stemmers_comparer.Requirement')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_email_address', models.EmailField(max_length=254)),
                ('user_github_account_link', models.CharField(max_length=255, null=True)),
                ('comment', models.TextField()),
                ('score', models.CharField(max_length=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('stemmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='stemmers_comparer.Stemmer')),
            ],
            options={
                'unique_together': {('user_email_address', 'stemmer')},
            },
        ),
    ]
