# Generated by Django 2.2 on 2019-04-20 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemmers_comparer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stemmer',
            options={},
        ),
    ]
