# Generated by Django 2.2 on 2019-04-24 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemmers_comparer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stemmer',
            options={'ordering': ['-average', '-count', 'display_name']},
        ),
        migrations.RemoveField(
            model_name='stemmer',
            name='total',
        ),
        migrations.AlterField(
            model_name='author',
            name='github_account_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='user_github_account_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together=set(),
        ),
    ]
