# Generated by Django 2.2 on 2019-04-23 05:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stemmers_comparer', '0002_auto_20190423_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('average', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('stemmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stemmers_comparer.Stemmer', unique=True)),
            ],
            options={
                'abstract': False,
                'swappable': 'STEMMERS_COMPARER_RATING_MODEL',
            },
        ),
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to=settings.STEMMERS_COMPARER_RATING_MODEL),
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
