# Generated by Django 2.2 on 2019-04-24 02:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemmers_comparer', '0002_auto_20190424_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stemmer',
            name='average',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=6),
        ),
    ]
