# Generated by Django 2.2 on 2019-04-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemmers_comparer', '0003_auto_20190420_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github_account_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
