# Generated by Django 2.2 on 2019-04-23 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stemmers_comparer', '0003_auto_20190423_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stemmer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stemmers_comparer.Stemmer'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to=settings.STEMMERS_COMPARER_RATING_MODEL),
        ),
    ]
