# Generated by Django 2.2 on 2019-04-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemmers_comparer', '0004_auto_20190423_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='github_account_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='content',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='content',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='stemmer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stemmer',
            name='display_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='stemmer',
            name='documentation_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stemmer',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stemmer',
            name='how_to_use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stemmer',
            name='license',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='comment',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='user_github_account_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
