# Generated by Django 2.2 on 2019-04-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemmers_comparer', '0004_auto_20190423_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='average',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='rating',
            name='count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='total',
            field=models.PositiveIntegerField(),
        ),
    ]
