# Generated by Django 2.2 on 2019-04-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemmers_comparer', '0005_auto_20190423_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
