# Generated by Django 2.2 on 2019-04-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemmers_comparer', '0005_auto_20190423_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='content',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='content',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='stemmer',
            name='authors',
            field=models.ManyToManyField(blank=True, to='stemmers_comparer.Author'),
        ),
        migrations.AlterField(
            model_name='stemmer',
            name='features',
            field=models.ManyToManyField(blank=True, to='stemmers_comparer.Feature'),
        ),
        migrations.AlterField(
            model_name='stemmer',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, to='stemmers_comparer.ProgrammingLanguage'),
        ),
        migrations.AlterField(
            model_name='stemmer',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='stemmers_comparer.Requirement'),
        ),
    ]
