# Generated by Django 2.2 on 2019-04-23 14:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemmers_comparer', '0006_auto_20190423_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='average',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6),
        ),
    ]
