# Generated by Django 2.2 on 2019-04-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemmers_comparer', '0008_auto_20190423_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrating',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='modified',
        ),
    ]
