# Generated by Django 2.2 on 2019-04-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemmers_comparer', '0010_auto_20190423_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
