# Generated by Django 2.2 on 2019-04-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemmers_comparer', '0011_auto_20190423_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='count',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
