# Generated by Django 2.2 on 2019-04-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemmers_comparer', '0012_auto_20190423_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='score',
            field=models.CharField(max_length=5),
        ),
    ]
