# Generated by Django 2.2 on 2019-04-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemmers_comparer', '0013_auto_20190423_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='count',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='rating',
            name='total',
            field=models.CharField(max_length=5),
        ),
    ]
