# Generated by Django 2.2 on 2019-04-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stemmers_comparer', '0014_auto_20190423_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrating',
            name='comment_date',
        ),
    ]
