# Generated by Django 2.2 on 2019-04-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemmers_comparer', '0015_remove_userrating_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
